### ISSUE TITLE
child pods stuck creating when using read only gcePersistentDisk

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/calrissian#79]
When running within google cloud k8s engine the pods created by calrissian to run various steps get stuck in the ContainerCreating state. The Events for these pods show 
AttachVolume.Attach failed for volume "<...gce pd name...> " : googleapi: Error 400: RESOURCE_IN_USE_BY_ANOTHER_RESOURCE - The disk resource '...gce pd name...' is already being used by '..k8s node..'

I think this might be fixed by declaring the persistentVolumeClaim as readOnly as described here:
https://github.com/kubernetes/kubernetes/issues/67313#issuecomment-417561428

**Comment by dleehr** [comment]
Thanks for the tip. I double-checked because I thought we were already doing this. We do set the Pod's `spec.containers.volumeMounts.readOnly` to true when the file is not writable:

https://github.com/Duke-GCB/calrissian/blob/aa2317b4ef00149896fc8c74bfece2f0b2c41bee/calrissian/job.py#L152-L158

But aren't setting it in `spec.containers.volumes.volume.persistentVolumeClaim`:

https://github.com/Duke-GCB/calrissian/blob/aa2317b4ef00149896fc8c74bfece2f0b2c41bee/calrissian/job.py#L106-L118

Looks like both should be set for GCEPersistentDisk.
